#!/bin/bash

################################
source /boot/config/plugins/cache-mover/cachemoversettings

### Check if another instance of this Program is running
pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Program $0 already running" && exit 1

################################
if [ "$unraid_syslog" == "yes" ]; then

log_message() {
  while IFS= read -r line; do
    logger "cache-cleaner: ${line}"
  done
}
exec > >(log_message) 2>&1

fi
### update rewrites once (can be removed sometime)
if [ ! -z $rewrite_source ] && [ ! -z $rewrite_host ]; then
        sed -i 's|^rewrite_source=.*|rewrite_source="'$rewrite_source':'$rewrite_host'"|g' /boot/config/plugins/cache-mover/cachemoversettings
        sed -i 's|^rewrite_host=.*||g' /boot/config/plugins/cache-mover/cachemoversettings
        sed -i '/^$/d' /boot/config/plugins/cache-mover/cachemoversettings
        echo "updated rewrites once"
fi

################################
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

### update permissions
touch $move_excl_list
touch $move_tune_list
chmod 777 $move_excl_list
chmod 777 $move_tune_list

### update mover ignore list ###
if [ "$move_excl" = "yes" ]; then
mover_source_files="$move_excl_list $move_tune_list"
### cleaning mover tuning list from empty directoty entries
	cat $move_tune_list | while read directorys
		do
			if [[ ! -d $directorys ]]; then
				sed -i "s|$directorys||g" $move_tune_list 2> /dev/null
			fi
		sed -i '/^[[:space:]]*$/d' $move_tune_list 2> /dev/null
		done
### updating list
	for mover_line in $mover_source_files
		do
		cat "$mover_line" >> moverfull
		done
	sort moverfull > moversorted
	uniq moversorted mover_excluded
	rm moverfull moversorted
	cp mover_excluded $move_tune_list
	rm mover_excluded
fi

sed -i '/^$/d' $move_tune_list
sed -i '/^$/d' $move_excl_list

exit;
