#!/bin/bash

################################
source /boot/config/plugins/cache-mover/cachemoversettings

################################
listupdater="/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover4"

### Check if another instance of this Program is running
pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Program $0 already running" && exit 1

################################
if [ "$unraid_syslog" == "yes" ]; then

log_message() {
  while IFS= read -r line; do
    logger "cache-mover: ${line}"
  done
}
exec > >(log_message) 2>&1

fi

## MediaServer Mode check
if [ "$mediaserver_only" == "only" ]; then
	/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover1
	exit;
fi

################################
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

### copy / mover lookup and action
for disk in $disks
	do
for subfolder in $subfolders
	do
for filetype in $filetypes
	do
	openfile=""
	openpath=""
	opencheck=""
	targetdir=""
	openfile=$(ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/mnt/$disk" | grep -i "/$subfolder" | grep -i "$filetype" | sed '$!d')
		if [ ! -z "$openfile" ]; then
			process_id=$(echo $openfile | awk '{ print $9; }' | cut -f 3 -d "/")
			file_descr=$(echo $openfile | awk '{ print $9; }' | cut -f 5 -d "/")
			openpath="$(readlink /proc/$process_id/fd/$file_descr)"
			### break if there is a exclusion match
			if [ ! -z "$exclusions" ]; then
			for excluded in $exclusions
				do
				if [[ "$openpath" == *"$excluded"* ]]; then
					echo "$excluded is excluded, we quit here";
					exit;
				fi
				done
			fi
			### break if file is in write mode
			write_check=$(echo $openfile | cut -f 1 -d " ")
			if [[ "$write_check" =~ ^lrw.* ]] || [[ "$write_check" =~ ^l-w.* ]]; then
				echo "$openpath is in write mode, we quit here"
				exit;
			fi
			directory=$(dirname "$openpath")
			echo "open dir on $disk: $directory"
			### wait and look if file is still open
			sleep $wait_todo
			opencheck=$(ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/mnt/$disk" | grep -i "/$subfolder" | grep -i "$filetype" | sed '$!d')
			### break if file is in write mode
			write_check=$(echo $opencheck | cut -f 1 -d " ")
			if [[ "$write_check" =~ ^lrw.* ]] || [[ "$write_check" =~ ^l-w.* ]]; then
				echo "$openpath is in write mode, we quit here"
				exit;
			fi
			opencheck="$(readlink /proc/$process_id/fd/$file_descr)"
			if [ "$openpath" == "$opencheck" ]; then
				targetdir=$(echo ${directory/$disk/$pool})
				echo "move / copy $directory/ to $targetdir/"
				mkdir -p "$targetdir"
				## move source files to target dir and delete file on array
				if [ "$rsync_mode" = "move" ]; then
					$rsync_move "$directory/" "$targetdir/"
					find "$directory" -type d -empty -delete
					if [ "$unraid_note" = "yes" ]; then
						/usr/local/emhttp/webGui/scripts/notify -e "Move Note" -s "$targetdir/" -i "normal" &
					fi
				fi
				## copy source files to target dir, keep Original
				if [ "$rsync_mode" = "copy" ]; then
					$rsync_copy "$directory/" "$targetdir/"
					if [ "$unraid_note" = "yes" ]; then
						/usr/local/emhttp/webGui/scripts/notify -e "Copy Note" -s "$targetdir/" -i "normal" &
					fi
				fi
				## add to mover tuning exclusion
				if [ "$move_excl" = "yes" ]; then
					echo "$targetdir" >> $move_excl_list
					awk -i inplace '!seen[$0]++' $move_excl_list
				fi
				## hard closing file descriptor path
				if [ "$switch_mode" = "close" ]; then
					echo "$directory/ open file will be closed"
					fdclose $process_id $file_descr
				fi
				## hard switching file descriptor path
				if [ "$switch_mode" = "switch" ]; then
				    echo "$openpath"
					echo "open file will be switched to new path"
					sleep 1
					dst=$(echo ${openpath/$disk/$pool})
					echo "$dst"
					if gdb --version > /dev/null 2>&1; then
						echo "ready to switch live"
					else
						echo "Unable to find gdb, check readme"
						exit 1
					fi
					(
					echo "attach $process_id"
					echo 'call (int)open("'$dst'", 00|0100|02000, 0666)'
					echo 'call (int)dup2($1,'$file_descr')'
					echo 'call (int)close($1)'
					echo 'detach'; echo 'quit'
					) | gdb -q -x -
				fi
			else
				echo "no copy/move for $directory"
			fi
		fi
	done
	done
	done

### update mover ignore list ###
$listupdater

### update access time on active pool disk
for subfolder in $subfolders
	do
for filetype in $filetypes
	do
		openfile=$(ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/mnt/$pool" | grep -i "/$subfolder" | grep -i "$filetype$" | sed '$!d')
		if [ ! -z "$openfile" ]; then
			process_id=$(echo $openfile | awk '{ print $9; }' | cut -f 3 -d "/")
			file_descr=$(echo $openfile | awk '{ print $9; }' | cut -f 5 -d "/")
			openpath="$(readlink /proc/$process_id/fd/$file_descr)"
			directory=$(dirname "$openpath")
			echo "update access time: $directory"
			touch -a "$directory"
			directory=$(dirname "$directory")
			touch -a "$directory"
		fi
	done
	done

## MediaServer Mode check
if [ "$mediaserver_only" == "multi" ]; then
	/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover1
	exit;
fi

exit;
