#!/bin/bash

################################
source /boot/config/plugins/cache-mover/cachemoversettings

### Check if another instance of this Program is running
pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Program $0 already running" && exit 1

################################
if [ "$unraid_syslog" == "yes" ]; then

log_message() {
  while IFS= read -r line; do
    logger "cache-cleaner: ${line}"
  done
}
exec > >(log_message) 2>&1

fi

################################
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

### update mover ignore list ###
if [ "$move_excl" = "yes" ]; then
mover_source_files="$move_excl_list $move_tune_list"

	for mover_line in $mover_source_files
	do
		cat "$mover_line" >> moverfull
	done
	sort moverfull > moversorted
	uniq moversorted mover_excluded
	rm moverfull moversorted
	cp mover_excluded $move_tune_list
	rm mover_excluded
fi

exit;